// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa4HGKRIPl25grMkEoj-Fzl5vbQWyS39g',
    appId: '1:144318179109:web:071b3e7a8a705c99e21ccc',
    messagingSenderId: '144318179109',
    projectId: 'ekal-4c5fd',
    authDomain: 'ekal-4c5fd.firebaseapp.com',
    storageBucket: 'ekal-4c5fd.appspot.com',
    measurementId: 'G-8DBK6XLCPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxRoPaw20XG5-W9IUTb38JooYCqu5RnBE',
    appId: '1:144318179109:android:97425f55860a19eae21ccc',
    messagingSenderId: '144318179109',
    projectId: 'ekal-4c5fd',
    storageBucket: 'ekal-4c5fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSon3FzpQP80sW-jowWK0wlGxN1_Fp5dg',
    appId: '1:144318179109:ios:6d66c8a07487bb11e21ccc',
    messagingSenderId: '144318179109',
    projectId: 'ekal-4c5fd',
    storageBucket: 'ekal-4c5fd.appspot.com',
    androidClientId: '144318179109-3jt8ufd8t82nnhp3tpiq64oc686gq696.apps.googleusercontent.com',
    iosClientId: '144318179109-bas4oc4rc2l6a200pdk9ll7j7i9anui7.apps.googleusercontent.com',
    iosBundleId: 'com.ispl.zinggyapp',
  );
}
